(package-install 'which-key)
(package-install 'company)
(package-install 'autopair)
(package-install 'company-quickhelp)
(package-install 'markdown-mode)
(package-install 'treemacs)
(package-install 'switch-window)
